externalSecrets: []
config:
  {
    apis: [],
    apiCredentials: [],
    apiEnvironments: []
  }
topology:
  proxyPerNode: false
  useTopologyKeys: false
httptoolkit:
  enable: false
  image: null
  ingress:
    enable: false
    hostname: null