apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: api-proxy
      context: fs
      sync:
        infer:
          - "src/**"
    # - image: api-proxy-httptoolkit
    #   context: httptoolkit
  local:
    useBuildkit: true
    useDockerCLI: true
    push: false
  tagPolicy:
    gitCommit:
      ignoreChanges: true
deploy:
  helm:
    releases:
      - name: api-proxy
        namespace: api-proxy
        createNamespace: true
        chartPath: chart
        artifactOverrides:
          image: api-proxy
          # httptoolkit.image: api-proxy-httptoolkit
        valuesFiles:
          - "./my-values.yaml"
portForward:
  - resourceType: service
    namespace: api-proxy
    resourceName: web
    port: 80
  - resourceType: service
    namespace: api-proxy
    resourceName: web
    port: 9229
    localPort: 9232
